name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          
      - name: Build
        run: cargo build --release
        
      - name: Generate Changelog
        run: |
          echo "# Changelog" > ${{ github.workspace }}-CHANGELOG.md
          echo "## ${{ github.ref_name }}" >> ${{ github.workspace }}-CHANGELOG.md
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s" >> ${{ github.workspace }}-CHANGELOG.md

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update version in static content
        run: |
          python .github/scripts/update_version.py

      - name: Create static content archive
        run: |
          cd public && zip -r ../mmoinsweeper-static-content.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.md
          files: |
            ./target/release/mmoinsweeper
            ./mmoinsweeper-static-content.zip
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
